USE `adserve`;
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('Google', 1, 1);
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('Pubmatic', 1, 1);
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('AppNexus', 1, 1);
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('RichAudience', 1, 1);
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('Unruly', 1, 1);
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('Improve Digital', 1, 1);
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('Index Exchange', 1, 1);
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('OpenX', 1, 1);
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('Synacor', 1, 1);
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('Sharethrouth', 1, 1);
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('EMX Digital', 1, 1);
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('Telaria', 1, 1);
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('Verizon Media/Yahoo SSP', 1, 1);
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('Conversant', 1, 1);
INSERT INTO demand_accounts (name, account_id, is_active) VALUES ('Rubicon/Magnite', 1, 1);
